### ISSUE TITLE
Frame rect vs. Layout (Alignment) rect of UI elements

### ISSUE THREAD

**Issue by cyclaero** [cjwl/cocotron#3]
I am working on the display optimization of NSComboBox elements which look somewhat rough in my Windows application:

![mac os x](https://cloud.githubusercontent.com/assets/13712142/9293983/dd3166dc-4414-11e5-81ad-346d38d158d9.png)![windows 7 rough](https://cloud.githubusercontent.com/assets/13712142/9293985/ecdfa31e-4414-11e5-846d-700aca86f261.png)

In NSComboCoxCell.m, I added the following private method:

```
- (void)_frame2layoutRect:(NSRect *)rect
{
   switch ([self controlSize])
   {
      case NSRegularControlSize:
         rect->size.width  -= 3.0;
         rect->size.height -= 4.0;
         break;

      case NSSmallControlSize:
         rect->size.width  -= 3.0;
         rect->size.height -= 3.0;
         break;

      case NSMiniControlSize:
         rect->size.width  -= 3.0;
         rect->size.height -= 4.0;
         break;
   }
}
```

Together with some minor changes to said cell implementation, the NSComboBox layout resembles much better its Mac OS X counterpart.

![windows 7 fine](https://cloud.githubusercontent.com/assets/13712142/9293987/f06cd57e-4414-11e5-9e75-0d35d5a498fc.png)

My question is now, is this the appropriate measure for tackling layout issues of UI elements, or do you have a better one in mind. There are a handfull of other elements which could benefit from some layout improvements as well, and I think it would be good to establish some sort of a model for doing it the right way.

**Comment by cjwl** [comment]
The first thing that comes to mind is the NSCell methods such as 
- titleRectForBounds:, 
- imageRectForBounds:,  
- drawWithFrame:inView:, 
- drawInteriorWithFrame:inView and related. There is typically a good enough relationship between these methods in the cell classes to make this kind of modification within the existing API, but it's figuring out that relationship which is the difficult piece.

**Comment by cyclaero** [comment]
OK! I am back working on the combo box. It got also other problems beyond simple layout displacements. Once I ironed out everything, I will commit the changes to my fork, and we may discuss that in more detail.

**Comment by cyclaero** [comment]
I finished rectification of NSComboBox appearance and behaviour and I commit the changes to my fork.
